# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:18-alpine AS builder

WORKDIR /app

# Copy the necessary files
COPY package.json package-lock.json ./
COPY tsconfig.json ./
COPY src ./src

# Install dependencies and build the project
RUN npm install && npm run build

# Use a smaller base image for the release
FROM node:18-alpine AS release

WORKDIR /app

# Copy only the built output and necessary files
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json

# Install production dependencies only
RUN npm install --production

# Set environment variable
ENV NODE_ENV=production

# Entry point
ENTRYPOINT ["node", "build/index.js"]